/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EditorialBoardRouteImport } from './routes/editorial-board'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadPageIdRouteImport } from './routes/read.$pageId'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminEditPageIdRouteImport } from './routes/admin.edit.$pageId'
import { Route as AdminBookBookIdRouteImport } from './routes/admin.book.$bookId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialBoardRoute = EditorialBoardRouteImport.update({
  id: '/editorial-board',
  path: '/editorial-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadPageIdRoute = ReadPageIdRouteImport.update({
  id: '/read/$pageId',
  path: '/read/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditPageIdRoute = AdminEditPageIdRouteImport.update({
  id: '/edit/$pageId',
  path: '/edit/$pageId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookBookIdRoute = AdminBookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/editorial-board': typeof EditorialBoardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/publications': typeof PublicationsRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$pageId': typeof ReadPageIdRoute
  '/admin/book/$bookId': typeof AdminBookBookIdRoute
  '/admin/edit/$pageId': typeof AdminEditPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/editorial-board': typeof EditorialBoardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/publications': typeof PublicationsRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$pageId': typeof ReadPageIdRoute
  '/admin/book/$bookId': typeof AdminBookBookIdRoute
  '/admin/edit/$pageId': typeof AdminEditPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/editorial-board': typeof EditorialBoardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/publications': typeof PublicationsRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$pageId': typeof ReadPageIdRoute
  '/admin/book/$bookId': typeof AdminBookBookIdRoute
  '/admin/edit/$pageId': typeof AdminEditPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/editorial-board'
    | '/library'
    | '/login'
    | '/publications'
    | '/signup'
    | '/admin/users'
    | '/book/$bookId'
    | '/read/$pageId'
    | '/admin/book/$bookId'
    | '/admin/edit/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/editorial-board'
    | '/library'
    | '/login'
    | '/publications'
    | '/signup'
    | '/admin/users'
    | '/book/$bookId'
    | '/read/$pageId'
    | '/admin/book/$bookId'
    | '/admin/edit/$pageId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/editorial-board'
    | '/library'
    | '/login'
    | '/publications'
    | '/signup'
    | '/admin/users'
    | '/book/$bookId'
    | '/read/$pageId'
    | '/admin/book/$bookId'
    | '/admin/edit/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  EditorialBoardRoute: typeof EditorialBoardRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PublicationsRoute: typeof PublicationsRoute
  SignupRoute: typeof SignupRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ReadPageIdRoute: typeof ReadPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-board': {
      id: '/editorial-board'
      path: '/editorial-board'
      fullPath: '/editorial-board'
      preLoaderRoute: typeof EditorialBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$pageId': {
      id: '/read/$pageId'
      path: '/read/$pageId'
      fullPath: '/read/$pageId'
      preLoaderRoute: typeof ReadPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$pageId': {
      id: '/admin/edit/$pageId'
      path: '/edit/$pageId'
      fullPath: '/admin/edit/$pageId'
      preLoaderRoute: typeof AdminEditPageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/book/$bookId': {
      id: '/admin/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/admin/book/$bookId'
      preLoaderRoute: typeof AdminBookBookIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminBookBookIdRoute: typeof AdminBookBookIdRoute
  AdminEditPageIdRoute: typeof AdminEditPageIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminBookBookIdRoute: AdminBookBookIdRoute,
  AdminEditPageIdRoute: AdminEditPageIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  EditorialBoardRoute: EditorialBoardRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PublicationsRoute: PublicationsRoute,
  SignupRoute: SignupRoute,
  BookBookIdRoute: BookBookIdRoute,
  ReadPageIdRoute: ReadPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
